# Generated by Django 3.0.7 on 2020-06-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='todo',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
