# Generated by Django 3.0.7 on 2020-07-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_auto_20200702_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='Coverletter',
            field=models.TextField(max_length=600),
        ),
    ]
